### ISSUE TITLE
Its not working?

### ISSUE THREAD

**Issue by henriquesaboya** [nidark/Poe-Companion#1]
Hello, not mean to be rude but i liked the macro idea and features, however it wont pop flasks neither properly detect my HP level. The ahk is properly updated, and i THINK the coordinates are ok, since i use the steam borderless window version. I even checked them, and they were like 1pixel off the preset ones.

I also set the primary skill on Q, and asked for it to pop 01110 flasks, and it didnt work also.

I did pressed alt f12

Am I missing something?

**Comment by henriquesaboya** [comment]
Hi, I messed up, it just doesnt work on dx9EX, made it for dx9 and worked properly =)

**Comment by nidark** [comment]
Sorry, I was out. 
Indeed I did my defaults on Dx11: i never realised they are differences for different Dx's. 
I will make this distinction from now on!
