### ISSUE TITLE
SeconaryAttackKey bug/error

### ISSUE THREAD

**Issue by PlatypusKing** [nidark/Poe-Companion#3]
Found a small error in the below code snippet.  It should be Trigger:=Trigger... instead of Trigger=:Trigger it was preventing the SecondaryAttack trigger from going off.

```
GetKeyState, state, %SecondaryAttackKey%
		if state = D
			Trigger=:Trigger+TriggerSecondaryAttack
```

should be

```
GetKeyState, state, %SecondaryAttackKey%
		if state = D
			Trigger:=Trigger+TriggerSecondaryAttack
```

**Comment by nidark** [comment]
Nice catch! I just changed :)
Unfortunately I am not playing and using this for some time (as you can notice from my late reply :))
